import { Product, Category } from "@/types";

export const categories: Category[] = [
  { name: "Orals", slug: "orals", description: "Oral anabolic steroids", color: "bg-red-600", icon: "💊" },
  { name: "Injectables", slug: "injectables", description: "Injectable steroids", color: "bg-blue-600", icon: "💉" },
  { name: "Peptides", slug: "peptides", description: "Peptides & growth hormones", color: "bg-purple-600", icon: "🧬" },
  { name: "PCT", slug: "pct", description: "Post cycle therapy", color: "bg-green-600", icon: "🛡️" },
  { name: "Fat Loss", slug: "fat-loss", description: "Fat burners & cutting agents", color: "bg-orange-600", icon: "🔥" },
  { name: "Sexual Health", slug: "sexual-health", description: "Sexual health products", color: "bg-pink-600", icon: "❤️" },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Anavar 10mg",
    slug: "anavar-10mg",
    category: "Orals",
    price: 85,
    originalPrice: 100,
    image: "/images/products/anavar-10mg.webp",
    description: "Oxandrolone 10mg per tablet. 100 tablets per bottle. A mild anabolic steroid ideal for cutting cycles and lean muscle preservation.",
    inStock: true,
    rating: 4.8,
    reviews: 124,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Dianabol 20mg",
    slug: "dianabol-20mg",
    category: "Orals",
    price: 65,
    originalPrice: 80,
    image: "/images/products/dianabol-20mg.webp",
    description: "Methandrostenolone 20mg per tablet. 100 tablets per bottle. One of the most popular oral steroids for mass and strength gains.",
    inStock: true,
    rating: 4.7,
    reviews: 98,
    badge: "Best Seller",
  },
  {
    id: "3",
    name: "Winstrol 50mg",
    slug: "winstrol-50mg",
    category: "Orals",
    price: 75,
    image: "/images/products/winstrol-50mg.webp",
    description: "Stanozolol 50mg per tablet. 100 tablets per bottle. Ideal for cutting cycles, promotes lean muscle and strength without water retention.",
    inStock: true,
    rating: 4.6,
    reviews: 87,
  },
  {
    id: "4",
    name: "Turinabol 10mg",
    slug: "turinabol-10mg",
    category: "Orals",
    price: 70,
    image: "/images/products/turinabol-10mg.webp",
    description: "Chlorodehydromethyltestosterone 10mg. 100 tablets. A mild oral steroid known for steady lean muscle gains.",
    inStock: true,
    rating: 4.5,
    reviews: 56,
    badge: "New",
  },
  {
    id: "5",
    name: "Anadrol 50mg",
    slug: "anadrol-50mg",
    category: "Orals",
    price: 80,
    originalPrice: 95,
    image: "/images/products/anadrol-50mg.webp",
    description: "Oxymetholone 50mg per tablet. 100 tablets per bottle. Powerful mass builder for serious bulking cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 73,
    badge: "Sale",
  },
  {
    id: "6",
    name: "Testosterone Enanthate 250",
    slug: "testosterone-enanthate-250",
    category: "Injectables",
    price: 55,
    image: "/images/products/testosterone-enanthate-250.webp",
    description: "Testosterone Enanthate 250mg/mL. 10mL vial. The most widely used injectable testosterone ester for bulking and performance.",
    inStock: true,
    rating: 4.9,
    reviews: 215,
    badge: "Best Seller",
  },
  {
    id: "7",
    name: "Testosterone Cypionate 250",
    slug: "testosterone-cypionate-250",
    category: "Injectables",
    price: 55,
    image: "/images/products/testosterone-cypionate-250.webp",
    description: "Testosterone Cypionate 250mg/mL. 10mL vial. Long-acting testosterone ester, popular in the US for TRT and performance use.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
  },
  {
    id: "8",
    name: "Deca 300",
    slug: "deca-300",
    category: "Injectables",
    price: 65,
    image: "/images/products/deca-300.webp",
    description: "Nandrolone Decanoate 300mg/mL. 10mL vial. Excellent for joint support and mass building cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 142,
    badge: "Best Seller",
  },
  {
    id: "9",
    name: "Trenbolone Acetate 100",
    slug: "trenbolone-acetate-100",
    category: "Injectables",
    price: 75,
    image: "/images/products/trenbolone-acetate-100.webp",
    description: "Trenbolone Acetate 100mg/mL. 10mL vial. One of the most potent steroids available for both cutting and bulking.",
    inStock: true,
    rating: 4.9,
    reviews: 189,
  },
  {
    id: "10",
    name: "Masteron Propionate 100",
    slug: "masteron-propionate-100",
    category: "Injectables",
    price: 70,
    image: "/images/products/masteron-propionate-100.webp",
    description: "Drostanolone Propionate 100mg/mL. 10mL vial. Popular cutting steroid that adds hardness and density.",
    inStock: true,
    rating: 4.6,
    reviews: 94,
    badge: "New",
  },
  {
    id: "11",
    name: "BPC-157 5mg",
    slug: "bpc-157-5mg",
    category: "Peptides",
    price: 45,
    image: "/images/products/bpc-157-5mg.webp",
    description: "BPC-157 5mg per vial. Body Protective Compound for accelerated healing of tendons, ligaments, and muscles.",
    inStock: true,
    rating: 4.8,
    reviews: 112,
    badge: "Best Seller",
  },
  {
    id: "12",
    name: "HGH 100IU",
    slug: "hgh-100iu",
    category: "Peptides",
    price: 180,
    originalPrice: 220,
    image: "/images/products/hgh-100iu.webp",
    description: "Human Growth Hormone 100IU kit. 10 x 10IU vials. For anti-aging, fat loss, and muscle recovery.",
    inStock: true,
    rating: 4.9,
    reviews: 203,
    badge: "Sale",
  },
  {
    id: "13",
    name: "TB-500 5mg",
    slug: "tb-500-5mg",
    category: "Peptides",
    price: 40,
    image: "/images/products/tb-500-5mg.webp",
    description: "Thymosin Beta-4 5mg per vial. Promotes healing and recovery of injuries, supports cardiovascular health.",
    inStock: true,
    rating: 4.7,
    reviews: 78,
  },
  {
    id: "14",
    name: "Nolvadex 20mg",
    slug: "nolvadex-20mg",
    category: "PCT",
    price: 50,
    image: "/images/products/nolvadex-20mg.webp",
    description: "Tamoxifen Citrate 20mg. 50 tablets. Essential PCT medication for estrogen control and restoring natural testosterone.",
    inStock: true,
    rating: 4.8,
    reviews: 156,
    badge: "Best Seller",
  },
  {
    id: "15",
    name: "Clomid 50mg",
    slug: "clomid-50mg",
    category: "PCT",
    price: 45,
    image: "/images/products/clomid-50mg.webp",
    description: "Clomiphene Citrate 50mg. 50 tablets. Commonly used post-cycle to restore natural hormone production.",
    inStock: true,
    rating: 4.7,
    reviews: 134,
    badge: "Best Seller",
  },
  {
    id: "16",
    name: "Aromasin 25mg",
    slug: "aromasin-25mg",
    category: "PCT",
    price: 60,
    image: "/images/products/aromasin-25mg.webp",
    description: "Exemestane 25mg. 30 tablets. Aromatase inhibitor for estrogen control on-cycle and during PCT.",
    inStock: true,
    rating: 4.6,
    reviews: 89,
  },
  {
    id: "17",
    name: "Clenbuterol 40mcg",
    slug: "clenbuterol-40mcg",
    category: "Fat Loss",
    price: 40,
    image: "/images/products/clenbuterol-40mcg.webp",
    description: "Clenbuterol Hydrochloride 40mcg. 100 tablets. Powerful thermogenic and bronchodilator for rapid fat loss.",
    inStock: true,
    rating: 4.7,
    reviews: 167,
    badge: "Best Seller",
  },
  {
    id: "18",
    name: "T3 Cytomel 25mcg",
    slug: "t3-cytomel-25mcg",
    category: "Fat Loss",
    price: 35,
    image: "/images/products/t3-cytomel-25mcg.webp",
    description: "Liothyronine Sodium 25mcg. 100 tablets. Thyroid hormone used for enhanced fat burning and metabolism boost.",
    inStock: true,
    rating: 4.6,
    reviews: 98,
  },
  {
    id: "19",
    name: "Cardarine GW-501516",
    slug: "cardarine-gw501516",
    category: "Fat Loss",
    price: 65,
    originalPrice: 80,
    image: "/images/products/cardarine-gw501516.webp",
    description: "GW-501516 10mg. 60 capsules. PPAR delta agonist for endurance, fat burning, and metabolic enhancement.",
    inStock: true,
    rating: 4.7,
    reviews: 121,
    badge: "Sale",
  },
  {
    id: "20",
    name: "Sildenafil 100mg",
    slug: "sildenafil-100mg",
    category: "Sexual Health",
    price: 30,
    image: "/images/products/sildenafil-100mg.webp",
    description: "Sildenafil Citrate 100mg. 50 tablets. PDE5 inhibitor for erectile dysfunction and sexual performance enhancement.",
    inStock: true,
    rating: 4.8,
    reviews: 203,
    badge: "Best Seller",
  },
  {
    id: "21",
    name: "Tadalafil 20mg",
    slug: "tadalafil-20mg",
    category: "Sexual Health",
    price: 35,
    image: "/images/products/tadalafil-20mg.webp",
    description: "Tadalafil 20mg. 50 tablets. Long-acting PDE5 inhibitor known as the weekend pill for sexual health.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase() || 
           p.category.toLowerCase().replace(" ", "-") === category.toLowerCase()
  );
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "Best Seller").slice(0, 8);
}
