import { Product, Category } from "@/types";

export const categories: Category[] = [
  { name: "Strength", slug: "strength", description: "Strength & performance supplements", color: "bg-green-600", icon: "💪" },
  { name: "Short Cycle", slug: "short-cycle", description: "Short half-life compounds", color: "bg-blue-500", icon: "⚡" },
  { name: "Sex", slug: "sex", description: "Sexual health & performance", color: "bg-pink-600", icon: "❤️" },
  { name: "Post Cycle Therapy", slug: "post-cycle-therapy", description: "PCT & hormone restoration", color: "bg-teal-600", icon: "🛡️" },
  { name: "Insulin", slug: "insulin", description: "Insulin & related products", color: "bg-indigo-600", icon: "💉" },
  { name: "Injectable Steroids", slug: "injectable-steroids", description: "Injectable anabolic steroids", color: "bg-blue-600", icon: "🔬" },
  { name: "HGH", slug: "hgh", description: "Human growth hormone", color: "bg-purple-600", icon: "🧬" },
  { name: "Fat Loss", slug: "fat-loss", description: "Fat burners & cutting agents", color: "bg-orange-600", icon: "🔥" },
  { name: "Bulking Steroids", slug: "bulking-steroids", description: "Mass & bulking compounds", color: "bg-red-600", icon: "🏋️" },
  { name: "Bac Water", slug: "bac-water", description: "Bacteriostatic water", color: "bg-cyan-600", icon: "💧" },
  { name: "Botox", slug: "botox", description: "Botulinum toxin products", color: "bg-rose-600", icon: "✨" },
];

export const products: Product[] = [
  // ── Strength ──────────────────────────────────────────────────────────────
  {
    id: "1",
    name: "Creatine Monohydrate 500g",
    slug: "creatine-monohydrate-500g",
    category: "Strength",
    price: 39,
    originalPrice: 49,
    image: "https://placehold.co/300x300/16a34a/ffffff?text=Creatine+500g",
    description: "Pure Creatine Monohydrate 500g. Increases muscle strength, power output and lean mass. Micronised for fast absorption.",
    inStock: true,
    rating: 4.8,
    reviews: 210,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Pre-Workout Extreme",
    slug: "pre-workout-extreme",
    category: "Strength",
    price: 55,
    originalPrice: 70,
    image: "https://placehold.co/300x300/16a34a/ffffff?text=Pre-Workout",
    description: "High-stimulant pre-workout formula. 300mg caffeine, beta-alanine, citrulline malate and L-tyrosine for peak training intensity.",
    inStock: true,
    rating: 4.7,
    reviews: 134,
    badge: "New",
  },
  {
    id: "3",
    name: "Beta-Alanine 300g",
    slug: "beta-alanine-300g",
    category: "Strength",
    price: 32,
    originalPrice: 42,
    image: "https://placehold.co/300x300/16a34a/ffffff?text=Beta-Alanine",
    description: "Beta-Alanine 3g per serving, 100 servings. Reduces muscle fatigue and increases muscular endurance during high-intensity exercise.",
    inStock: true,
    rating: 4.6,
    reviews: 89,
    badge: "New",
  },

  // ── Short Cycle ────────────────────────────────────────────────────────────
  {
    id: "4",
    name: "Testosterone Propionate 100",
    slug: "testosterone-propionate-100",
    category: "Short Cycle",
    price: 50,
    originalPrice: 65,
    image: "https://placehold.co/300x300/3b82f6/ffffff?text=Test+Prop+100",
    description: "Testosterone Propionate 100mg/mL. 10mL vial. Fast-acting testosterone ester ideal for short cycles and cutting phases.",
    inStock: true,
    rating: 4.8,
    reviews: 162,
    badge: "New",
  },
  {
    id: "5",
    name: "Trenbolone Acetate 100",
    slug: "trenbolone-acetate-100",
    category: "Short Cycle",
    price: 75,
    originalPrice: 90,
    image: "https://placehold.co/300x300/3b82f6/ffffff?text=Tren+Ace+100",
    description: "Trenbolone Acetate 100mg/mL. 10mL vial. One of the most potent steroids available for both cutting and bulking short cycles.",
    inStock: true,
    rating: 4.9,
    reviews: 189,
    badge: "Best Seller",
  },
  {
    id: "6",
    name: "Masteron Propionate 100",
    slug: "masteron-propionate-100",
    category: "Short Cycle",
    price: 65,
    originalPrice: 80,
    image: "https://placehold.co/300x300/3b82f6/ffffff?text=Mast+Prop+100",
    description: "Drostanolone Propionate 100mg/mL. 10mL vial. Popular cutting steroid that adds hardness and density. Ideal for short cycles.",
    inStock: true,
    rating: 4.6,
    reviews: 94,
    badge: "New",
  },

  // ── Sex ───────────────────────────────────────────────────────────────────
  {
    id: "7",
    name: "Sildenafil 100mg",
    slug: "sildenafil-100mg",
    category: "Sex",
    price: 30,
    originalPrice: 40,
    image: "https://placehold.co/300x300/db2777/ffffff?text=Sildenafil+100mg",
    description: "Sildenafil Citrate 100mg. 50 tablets. PDE5 inhibitor for erectile dysfunction and sexual performance enhancement.",
    inStock: true,
    rating: 4.8,
    reviews: 203,
    badge: "Best Seller",
  },
  {
    id: "8",
    name: "Tadalafil 20mg",
    slug: "tadalafil-20mg",
    category: "Sex",
    price: 35,
    originalPrice: 48,
    image: "https://placehold.co/300x300/db2777/ffffff?text=Tadalafil+20mg",
    description: "Tadalafil 20mg. 50 tablets. Long-acting PDE5 inhibitor known as the weekend pill, effective for up to 36 hours.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
    badge: "New",
  },
  {
    id: "9",
    name: "PT-141 Bremelanotide 10mg",
    slug: "pt-141-10mg",
    category: "Sex",
    price: 60,
    originalPrice: 78,
    image: "https://placehold.co/300x300/db2777/ffffff?text=PT-141+10mg",
    description: "Bremelanotide PT-141 10mg per vial. Melanocortin receptor agonist for sexual dysfunction in both men and women.",
    inStock: true,
    rating: 4.7,
    reviews: 97,
    badge: "New",
  },

  // ── Post Cycle Therapy ─────────────────────────────────────────────────────
  {
    id: "10",
    name: "Nolvadex 20mg",
    slug: "nolvadex-20mg",
    category: "Post Cycle Therapy",
    price: 50,
    originalPrice: 62,
    image: "https://placehold.co/300x300/0d9488/ffffff?text=Nolvadex+20mg",
    description: "Tamoxifen Citrate 20mg. 50 tablets. Essential PCT medication for estrogen control and restoring natural testosterone.",
    inStock: true,
    rating: 4.8,
    reviews: 156,
    badge: "Best Seller",
  },
  {
    id: "11",
    name: "Clomid 50mg",
    slug: "clomid-50mg",
    category: "Post Cycle Therapy",
    price: 45,
    originalPrice: 58,
    image: "https://placehold.co/300x300/0d9488/ffffff?text=Clomid+50mg",
    description: "Clomiphene Citrate 50mg. 50 tablets. Commonly used post-cycle to restore natural hormone production.",
    inStock: true,
    rating: 4.7,
    reviews: 134,
    badge: "Best Seller",
  },
  {
    id: "12",
    name: "Aromasin 25mg",
    slug: "aromasin-25mg",
    category: "Post Cycle Therapy",
    price: 55,
    originalPrice: 72,
    image: "https://placehold.co/300x300/0d9488/ffffff?text=Aromasin+25mg",
    description: "Exemestane 25mg. 30 tablets. Aromatase inhibitor for estrogen control on-cycle and during PCT.",
    inStock: true,
    rating: 4.6,
    reviews: 89,
    badge: "New",
  },

  // ── Insulin ────────────────────────────────────────────────────────────────
  {
    id: "13",
    name: "Humalog 100IU/mL",
    slug: "humalog-100iu",
    category: "Insulin",
    price: 45,
    originalPrice: 58,
    image: "https://placehold.co/300x300/4f46e5/ffffff?text=Humalog+100IU",
    description: "Insulin Lispro (Humalog) 100IU/mL. 10mL vial. Rapid-acting insulin analog for post-workout nutrient uptake.",
    inStock: true,
    rating: 4.8,
    reviews: 112,
    badge: "Best Seller",
  },
  {
    id: "14",
    name: "NovoRapid 100IU/mL",
    slug: "novorapid-100iu",
    category: "Insulin",
    price: 48,
    originalPrice: 62,
    image: "https://placehold.co/300x300/4f46e5/ffffff?text=NovoRapid+100IU",
    description: "Insulin Aspart (NovoRapid) 100IU/mL. 10mL vial. Ultra fast-acting insulin for optimal nutrient partitioning.",
    inStock: true,
    rating: 4.7,
    reviews: 78,
    badge: "New",
  },
  {
    id: "15",
    name: "Insulin Syringe Pack (100)",
    slug: "insulin-syringe-pack",
    category: "Insulin",
    price: 22,
    originalPrice: 30,
    image: "https://placehold.co/300x300/4f46e5/ffffff?text=Insulin+Syringes",
    description: "1mL U-100 insulin syringes with 29G x 1/2\" needle. Pack of 100. Sterile, single-use for precise dosing.",
    inStock: true,
    rating: 4.9,
    reviews: 245,
    badge: "New",
  },

  // ── Injectable Steroids ────────────────────────────────────────────────────
  {
    id: "16",
    name: "Testosterone Enanthate 250",
    slug: "testosterone-enanthate-250",
    category: "Injectable Steroids",
    price: 55,
    originalPrice: 68,
    image: "https://placehold.co/300x300/1d4ed8/ffffff?text=Test+E+250",
    description: "Testosterone Enanthate 250mg/mL. 10mL vial. The most widely used injectable testosterone ester for bulking and performance.",
    inStock: true,
    rating: 4.9,
    reviews: 215,
    badge: "Best Seller",
  },
  {
    id: "17",
    name: "Testosterone Cypionate 250",
    slug: "testosterone-cypionate-250",
    category: "Injectable Steroids",
    price: 55,
    originalPrice: 68,
    image: "https://placehold.co/300x300/1d4ed8/ffffff?text=Test+C+250",
    description: "Testosterone Cypionate 250mg/mL. 10mL vial. Long-acting testosterone ester, popular for TRT and performance use.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
    badge: "New",
  },
  {
    id: "18",
    name: "Deca 300",
    slug: "deca-300",
    category: "Injectable Steroids",
    price: 65,
    originalPrice: 80,
    image: "https://placehold.co/300x300/1d4ed8/ffffff?text=Deca+300",
    description: "Nandrolone Decanoate 300mg/mL. 10mL vial. Excellent for joint support and mass building cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 142,
    badge: "Best Seller",
  },
  {
    id: "19",
    name: "Sustanon 270",
    slug: "sustanon-270",
    category: "Injectable Steroids",
    price: 60,
    originalPrice: 75,
    image: "https://placehold.co/300x300/1d4ed8/ffffff?text=Sustanon+270",
    description: "Sustanon 270mg/mL blend of four testosterone esters. 10mL vial. Provides both rapid and sustained testosterone release.",
    inStock: true,
    rating: 4.8,
    reviews: 163,
    badge: "New",
  },
  {
    id: "20",
    name: "EQ 300 (Boldenone)",
    slug: "eq-300",
    category: "Injectable Steroids",
    price: 68,
    originalPrice: 85,
    image: "https://placehold.co/300x300/1d4ed8/ffffff?text=EQ+300",
    description: "Boldenone Undecylenate 300mg/mL. 10mL vial. Increases appetite and promotes quality lean muscle gains with low side effects.",
    inStock: true,
    rating: 4.6,
    reviews: 101,
    badge: "Sale",
  },

  // ── HGH ───────────────────────────────────────────────────────────────────
  {
    id: "21",
    name: "HGH 100IU Kit",
    slug: "hgh-100iu",
    category: "HGH",
    price: 180,
    originalPrice: 225,
    image: "https://placehold.co/300x300/7e22ce/ffffff?text=HGH+100IU",
    description: "Human Growth Hormone 100IU kit. 10 x 10IU vials. For anti-aging, fat loss, and muscle recovery.",
    inStock: true,
    rating: 4.9,
    reviews: 203,
    badge: "Sale",
  },
  {
    id: "22",
    name: "Ipamorelin 5mg",
    slug: "ipamorelin-5mg",
    category: "HGH",
    price: 42,
    originalPrice: 58,
    image: "https://placehold.co/300x300/7e22ce/ffffff?text=Ipamorelin+5mg",
    description: "Ipamorelin 5mg per vial. Selective growth hormone secretagogue with no cortisol or prolactin elevation. Ideal for anti-aging.",
    inStock: true,
    rating: 4.7,
    reviews: 86,
    badge: "New",
  },
  {
    id: "23",
    name: "GHRP-6 5mg",
    slug: "ghrp-6-5mg",
    category: "HGH",
    price: 38,
    originalPrice: 52,
    image: "https://placehold.co/300x300/7e22ce/ffffff?text=GHRP-6+5mg",
    description: "GHRP-6 5mg per vial. Growth Hormone Releasing Peptide-6 that stimulates GH release and increases appetite.",
    inStock: true,
    rating: 4.6,
    reviews: 72,
    badge: "New",
  },

  // ── Fat Loss ───────────────────────────────────────────────────────────────
  {
    id: "24",
    name: "Clenbuterol 40mcg",
    slug: "clenbuterol-40mcg",
    category: "Fat Loss",
    price: 38,
    originalPrice: 50,
    image: "https://placehold.co/300x300/ea580c/ffffff?text=Clen+40mcg",
    description: "Clenbuterol Hydrochloride 40mcg. 100 tablets. Powerful thermogenic and bronchodilator for rapid fat loss.",
    inStock: true,
    rating: 4.7,
    reviews: 167,
    badge: "Best Seller",
  },
  {
    id: "25",
    name: "T3 Cytomel 25mcg",
    slug: "t3-cytomel-25mcg",
    category: "Fat Loss",
    price: 32,
    originalPrice: 45,
    image: "https://placehold.co/300x300/ea580c/ffffff?text=T3+25mcg",
    description: "Liothyronine Sodium 25mcg. 100 tablets. Thyroid hormone used for enhanced fat burning and metabolism boost.",
    inStock: true,
    rating: 4.6,
    reviews: 98,
    badge: "New",
  },
  {
    id: "26",
    name: "Cardarine GW-501516",
    slug: "cardarine-gw501516",
    category: "Fat Loss",
    price: 58,
    originalPrice: 75,
    image: "https://placehold.co/300x300/ea580c/ffffff?text=Cardarine+GW",
    description: "GW-501516 10mg. 60 capsules. PPAR delta agonist for endurance, fat burning, and metabolic enhancement.",
    inStock: true,
    rating: 4.7,
    reviews: 121,
    badge: "Sale",
  },

  // ── Bulking Steroids ───────────────────────────────────────────────────────
  {
    id: "27",
    name: "Dianabol 20mg",
    slug: "dianabol-20mg",
    category: "Bulking Steroids",
    price: 60,
    originalPrice: 78,
    image: "https://placehold.co/300x300/dc2626/ffffff?text=Dianabol+20mg",
    description: "Methandrostenolone 20mg per tablet. 100 tablets per bottle. One of the most popular oral steroids for mass and strength gains.",
    inStock: true,
    rating: 4.7,
    reviews: 98,
    badge: "Best Seller",
  },
  {
    id: "28",
    name: "Anadrol 50mg",
    slug: "anadrol-50mg",
    category: "Bulking Steroids",
    price: 75,
    originalPrice: 95,
    image: "https://placehold.co/300x300/dc2626/ffffff?text=Anadrol+50mg",
    description: "Oxymetholone 50mg per tablet. 100 tablets per bottle. Powerful mass builder for serious bulking cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 73,
    badge: "Sale",
  },
  {
    id: "29",
    name: "Anavar 50mg",
    slug: "anavar-50mg",
    category: "Bulking Steroids",
    price: 90,
    originalPrice: 115,
    image: "https://placehold.co/300x300/dc2626/ffffff?text=Anavar+50mg",
    description: "Oxandrolone 50mg per tablet. 60 tablets per bottle. Higher-dose Anavar for significant strength and lean mass gains.",
    inStock: true,
    rating: 4.8,
    reviews: 108,
    badge: "New",
  },
  {
    id: "30",
    name: "Turinabol 10mg",
    slug: "turinabol-10mg",
    category: "Bulking Steroids",
    price: 65,
    originalPrice: 82,
    image: "https://placehold.co/300x300/dc2626/ffffff?text=Turinabol+10mg",
    description: "Chlorodehydromethyltestosterone 10mg. 100 tablets. A mild oral steroid known for steady lean muscle gains without water retention.",
    inStock: true,
    rating: 4.5,
    reviews: 56,
    badge: "New",
  },

  // ── Bac Water ─────────────────────────────────────────────────────────────
  {
    id: "31",
    name: "Bacteriostatic Water 30mL",
    slug: "bac-water-30ml",
    category: "Bac Water",
    price: 14,
    originalPrice: 20,
    image: "https://placehold.co/300x300/0891b2/ffffff?text=Bac+Water+30mL",
    description: "Bacteriostatic Water 0.9% benzyl alcohol. 30mL multi-dose vial. Used for reconstituting lyophilized peptides and HGH.",
    inStock: true,
    rating: 4.9,
    reviews: 312,
    badge: "Best Seller",
  },
  {
    id: "32",
    name: "Bacteriostatic Water 10mL",
    slug: "bac-water-10ml",
    category: "Bac Water",
    price: 8,
    originalPrice: 12,
    image: "https://placehold.co/300x300/0891b2/ffffff?text=Bac+Water+10mL",
    description: "Bacteriostatic Water 0.9% benzyl alcohol. 10mL vial. Sterile water for injections and peptide reconstitution.",
    inStock: true,
    rating: 4.9,
    reviews: 278,
    badge: "New",
  },

  // ── Botox ──────────────────────────────────────────────────────────────────
  {
    id: "33",
    name: "Botox 100U (Botulinum Type A)",
    slug: "botox-100u",
    category: "Botox",
    price: 115,
    originalPrice: 150,
    image: "https://placehold.co/300x300/be185d/ffffff?text=Botox+100U",
    description: "Botulinum Toxin Type A 100 Units. Pharmaceutical grade for cosmetic use. Reduces fine lines, wrinkles, and hyperhidrosis.",
    inStock: true,
    rating: 4.8,
    reviews: 145,
    badge: "New",
  },
  {
    id: "34",
    name: "Botox 200U (Botulinum Type A)",
    slug: "botox-200u",
    category: "Botox",
    price: 210,
    originalPrice: 275,
    image: "https://placehold.co/300x300/be185d/ffffff?text=Botox+200U",
    description: "Botulinum Toxin Type A 200 Units. Value pack for professional cosmetic treatments. Pharmaceutical grade purity.",
    inStock: true,
    rating: 4.9,
    reviews: 88,
    badge: "New",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase() || 
           p.category.toLowerCase().replace(/\s+/g, "-") === category.toLowerCase()
  );
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "Best Seller").slice(0, 8);
}
