import { Product, Category } from "@/types";

export const categories: Category[] = [
  { name: "Short Cycle", slug: "short-cycle", description: "Short half-life compounds", color: "bg-blue-500", icon: "⚡", image: "/images/products/trenbolone-acetate-100.webp" },
  { name: "Sex", slug: "sex", description: "Sexual health & performance", color: "bg-pink-600", icon: "❤️", image: "/images/products/sildenafil-100mg.webp" },
  { name: "Post Cycle Therapy", slug: "post-cycle-therapy", description: "PCT & hormone restoration", color: "bg-teal-600", icon: "🛡️", image: "/images/products/nolvadex-20mg.webp" },
  { name: "Injectable Steroids", slug: "injectable-steroids", description: "Injectable anabolic steroids", color: "bg-blue-600", icon: "🔬", image: "/images/products/testosterone-enanthate-250.webp" },
  { name: "HGH", slug: "hgh", description: "Human growth hormone & peptides", color: "bg-purple-600", icon: "🧬", image: "/images/products/hgh-100iu.webp" },
  { name: "Fat Loss", slug: "fat-loss", description: "Fat burners & cutting agents", color: "bg-orange-600", icon: "🔥", image: "/images/products/clenbuterol-40mcg.webp" },
  { name: "Bulking Steroids", slug: "bulking-steroids", description: "Mass & bulking compounds", color: "bg-red-600", icon: "🏋️", image: "/images/products/dianabol-20mg.webp" },
];

export const products: Product[] = [
  // ── Short Cycle ────────────────────────────────────────────────────────────
  {
    id: "5",
    name: "Trenbolone Acetate 100",
    slug: "trenbolone-acetate-100",
    category: "Short Cycle",
    price: 75,
    originalPrice: 90,
    image: "/images/products/trenbolone-acetate-100.webp",
    description: "Trenbolone Acetate 100mg/mL. 10mL vial. One of the most potent steroids available for both cutting and bulking short cycles.",
    inStock: true,
    rating: 4.9,
    reviews: 189,
    badge: "Best Seller",
    unitsPerPack: 1,
    dosePerUnit: "100mg/mL (10mL vial)",
  },
  {
    id: "6",
    name: "Masteron Propionate 100",
    slug: "masteron-propionate-100",
    category: "Short Cycle",
    price: 65,
    originalPrice: 80,
    image: "/images/products/masteron-propionate-100.webp",
    description: "Drostanolone Propionate 100mg/mL. 10mL vial. Popular cutting steroid that adds hardness and density. Ideal for short cycles.",
    inStock: true,
    rating: 4.6,
    reviews: 94,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "100mg/mL (10mL vial)",
  },

  // ── Sex ───────────────────────────────────────────────────────────────────
  {
    id: "7",
    name: "Sildenafil 100mg",
    slug: "sildenafil-100mg",
    category: "Sex",
    price: 30,
    originalPrice: 40,
    image: "/images/products/sildenafil-100mg.webp",
    description: "Sildenafil Citrate 100mg. 50 tablets. PDE5 inhibitor for erectile dysfunction and sexual performance enhancement.",
    inStock: true,
    rating: 4.8,
    reviews: 203,
    badge: "Best Seller",
    unitsPerPack: 50,
    dosePerUnit: "100mg",
  },
  {
    id: "8",
    name: "Tadalafil 20mg",
    slug: "tadalafil-20mg",
    category: "Sex",
    price: 35,
    originalPrice: 48,
    image: "/images/products/tadalafil-20mg.webp",
    description: "Tadalafil 20mg. 50 tablets. Long-acting PDE5 inhibitor known as the weekend pill, effective for up to 36 hours.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
    badge: "New",
    unitsPerPack: 50,
    dosePerUnit: "20mg",
  },

  // ── Post Cycle Therapy ─────────────────────────────────────────────────────
  {
    id: "10",
    name: "Nolvadex 20mg",
    slug: "nolvadex-20mg",
    category: "Post Cycle Therapy",
    price: 50,
    originalPrice: 62,
    image: "/images/products/nolvadex-20mg.webp",
    description: "Tamoxifen Citrate 20mg. 50 tablets. Essential PCT medication for estrogen control and restoring natural testosterone.",
    inStock: true,
    rating: 4.8,
    reviews: 156,
    badge: "Best Seller",
    unitsPerPack: 50,
    dosePerUnit: "20mg",
  },
  {
    id: "11",
    name: "Clomid 50mg",
    slug: "clomid-50mg",
    category: "Post Cycle Therapy",
    price: 45,
    originalPrice: 58,
    image: "/images/products/clomid-50mg.webp",
    description: "Clomiphene Citrate 50mg. 50 tablets. Commonly used post-cycle to restore natural hormone production.",
    inStock: true,
    rating: 4.7,
    reviews: 134,
    badge: "Best Seller",
    unitsPerPack: 50,
    dosePerUnit: "50mg",
  },
  {
    id: "12",
    name: "Aromasin 25mg",
    slug: "aromasin-25mg",
    category: "Post Cycle Therapy",
    price: 55,
    originalPrice: 72,
    image: "/images/products/aromasin-25mg.webp",
    description: "Exemestane 25mg. 30 tablets. Aromatase inhibitor for estrogen control on-cycle and during PCT.",
    inStock: true,
    rating: 4.6,
    reviews: 89,
    badge: "New",
    unitsPerPack: 30,
    dosePerUnit: "25mg",
  },

  // ── Injectable Steroids ────────────────────────────────────────────────────
  {
    id: "16",
    name: "Testosterone Enanthate 250",
    slug: "testosterone-enanthate-250",
    category: "Injectable Steroids",
    price: 55,
    originalPrice: 68,
    image: "/images/products/testosterone-enanthate-250.webp",
    licenceUrl: "/images/products/enantat-250-2913--s256.webp",
    description: "Testosterone Enanthate 250mg/mL. 10mL vial. The most widely used injectable testosterone ester for bulking and performance.",
    inStock: true,
    rating: 4.9,
    reviews: 215,
    badge: "Best Seller",
    unitsPerPack: 1,
    dosePerUnit: "250mg/mL (10mL vial)",
  },
  {
    id: "17",
    name: "Testosterone Cypionate 250",
    slug: "testosterone-cypionate-250",
    category: "Injectable Steroids",
    price: 55,
    originalPrice: 68,
    image: "/images/products/testosterone-cypionate-250.webp",
    licenceUrl: "/images/products/cypionat-250-2917--s256.webp",
    description: "Testosterone Cypionate 250mg/mL. 10mL vial. Long-acting testosterone ester, popular for TRT and performance use.",
    inStock: true,
    rating: 4.8,
    reviews: 178,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "250mg/mL (10mL vial)",
  },
  {
    id: "18",
    name: "Deca 300",
    slug: "deca-300",
    category: "Injectable Steroids",
    price: 65,
    originalPrice: 80,
    image: "/images/products/deca-300.webp",
    licenceUrl: "/images/products/deca-300-2911--s256.webp",
    description: "Nandrolone Decanoate 300mg/mL. 10mL vial. Excellent for joint support and mass building cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 142,
    badge: "Best Seller",
    unitsPerPack: 1,
    dosePerUnit: "300mg/mL (10mL vial)",
  },
  {
    id: "19",
    name: "Sustanon 270",
    slug: "sustanon-270",
    category: "Injectable Steroids",
    price: 60,
    originalPrice: 75,
    image: "/images/products/sustanon-270.webp",
    licenceUrl: "/images/products/sustanon-270-2912--s256.webp",
    description: "Sustanon 270mg/mL blend of four testosterone esters. 10mL vial. Provides both rapid and sustained testosterone release.",
    inStock: true,
    rating: 4.8,
    reviews: 163,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "270mg/mL (10mL vial)",
  },
  {
    id: "20",
    name: "EQ 300 (Boldenone)",
    slug: "eq-300",
    category: "Injectable Steroids",
    price: 68,
    originalPrice: 85,
    image: "/images/products/eq-300.webp",
    licenceUrl: "/images/products/eq-300-2916--s256.webp",
    description: "Boldenone Undecylenate 300mg/mL. 10mL vial. Increases appetite and promotes quality lean muscle gains with low side effects.",
    inStock: true,
    rating: 4.6,
    reviews: 101,
    badge: "Sale",
    unitsPerPack: 1,
    dosePerUnit: "300mg/mL (10mL vial)",
  },
  {
    id: "35",
    name: "Cut Long 300",
    slug: "cut-long-300",
    category: "Injectable Steroids",
    price: 72,
    originalPrice: 90,
    image: "/images/products/cut-long-300-2960--s256.webp",
    description: "Cut Long 300mg/mL blend. 10mL vial. A powerful cutting blend for lean muscle retention and fat loss during a caloric deficit.",
    inStock: true,
    rating: 4.7,
    reviews: 88,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "300mg/mL (10mL vial)",
  },

  // ── HGH ───────────────────────────────────────────────────────────────────
  {
    id: "21",
    name: "HGH 100IU Kit",
    slug: "hgh-100iu",
    category: "HGH",
    price: 180,
    originalPrice: 225,
    image: "/images/products/hgh-100iu.webp",
    licenceUrl: "/images/products/dragontropin-hgh-100-iu-46298--s256.webp",
    description: "Human Growth Hormone 100IU kit. 10 x 10IU vials. For anti-aging, fat loss, and muscle recovery.",
    inStock: true,
    rating: 4.9,
    reviews: 203,
    badge: "Sale",
    unitsPerPack: 10,
    dosePerUnit: "10IU per vial",
  },
  {
    id: "36",
    name: "BPC-157 5mg",
    slug: "bpc-157-5mg",
    category: "HGH",
    price: 45,
    originalPrice: 60,
    image: "/images/products/bpc-157-5mg.webp",
    licenceUrl: "/images/products/bpc-157-48731--s256.webp",
    description: "BPC-157 5mg per vial. Body protection compound peptide known for accelerating healing of tendons, ligaments, and gut tissue.",
    inStock: true,
    rating: 4.8,
    reviews: 112,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "5mg per vial",
  },
  {
    id: "37",
    name: "TB-500 5mg",
    slug: "tb-500-5mg",
    category: "HGH",
    price: 48,
    originalPrice: 62,
    image: "/images/products/tb-500-5mg.webp",
    description: "Thymosin Beta-4 (TB-500) 5mg per vial. Synthetic peptide for rapid tissue repair, reduced inflammation, and improved flexibility.",
    inStock: true,
    rating: 4.7,
    reviews: 95,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "5mg per vial",
  },

  // ── Fat Loss ───────────────────────────────────────────────────────────────
  {
    id: "24",
    name: "Clenbuterol 40mcg",
    slug: "clenbuterol-40mcg",
    category: "Fat Loss",
    price: 38,
    originalPrice: 50,
    image: "/images/products/clenbuterol-40mcg.webp",
    licenceUrl: "/images/products/clenbuterol-3166--s256.webp",
    description: "Clenbuterol Hydrochloride 40mcg. 100 tablets. Powerful thermogenic and bronchodilator for rapid fat loss.",
    inStock: true,
    rating: 4.7,
    reviews: 167,
    badge: "Best Seller",
    unitsPerPack: 100,
    dosePerUnit: "40mcg",
  },
  {
    id: "25",
    name: "T3 Cytomel 25mcg",
    slug: "t3-cytomel-25mcg",
    category: "Fat Loss",
    price: 32,
    originalPrice: 45,
    image: "/images/products/t3-cytomel-25mcg.webp",
    description: "Liothyronine Sodium 25mcg. 100 tablets. Thyroid hormone used for enhanced fat burning and metabolism boost.",
    inStock: true,
    rating: 4.6,
    reviews: 98,
    badge: "New",
    unitsPerPack: 100,
    dosePerUnit: "25mcg",
  },
  {
    id: "26",
    name: "Cardarine GW-501516",
    slug: "cardarine-gw501516",
    category: "Fat Loss",
    price: 58,
    originalPrice: 75,
    image: "/images/products/cardarine-gw501516.webp",
    description: "GW-501516 10mg. 60 capsules. PPAR delta agonist for endurance, fat burning, and metabolic enhancement.",
    inStock: true,
    rating: 4.7,
    reviews: 121,
    badge: "Sale",
    unitsPerPack: 60,
    dosePerUnit: "10mg",
  },
  {
    id: "38",
    name: "Mazdutide 10mg",
    slug: "mazdutide-10mg",
    category: "Fat Loss",
    price: 95,
    originalPrice: 120,
    image: "/images/products/mazdutide-10-mg-74034--s256.webp",
    description: "Mazdutide (IBI362) 10mg per vial. GLP-1/glucagon dual receptor agonist for significant weight loss and metabolic improvement.",
    inStock: true,
    rating: 4.8,
    reviews: 64,
    badge: "New",
    unitsPerPack: 1,
    dosePerUnit: "10mg per vial",
  },

  // ── Bulking Steroids ───────────────────────────────────────────────────────
  {
    id: "27",
    name: "Dianabol 20mg",
    slug: "dianabol-20mg",
    category: "Bulking Steroids",
    price: 60,
    originalPrice: 78,
    image: "/images/products/dianabol-20mg.webp",
    licenceUrl: "/images/products/dianabol-20-2807--s256.webp",
    description: "Methandrostenolone 20mg per tablet. 100 tablets per bottle. One of the most popular oral steroids for mass and strength gains.",
    inStock: true,
    rating: 4.7,
    reviews: 98,
    badge: "Best Seller",
    unitsPerPack: 100,
    dosePerUnit: "20mg",
  },
  {
    id: "28",
    name: "Anadrol 50mg",
    slug: "anadrol-50mg",
    category: "Bulking Steroids",
    price: 75,
    originalPrice: 95,
    image: "/images/products/anadrol-50mg.webp",
    description: "Oxymetholone 50mg per tablet. 100 tablets per bottle. Powerful mass builder for serious bulking cycles.",
    inStock: true,
    rating: 4.7,
    reviews: 73,
    badge: "Sale",
    unitsPerPack: 100,
    dosePerUnit: "50mg",
  },
  {
    id: "39",
    name: "Anavar 10mg",
    slug: "anavar-10mg",
    category: "Bulking Steroids",
    price: 65,
    originalPrice: 82,
    image: "/images/products/anavar-10mg.webp",
    licenceUrl: "/images/products/anavar-10-2838--s256.webp",
    description: "Oxandrolone 10mg per tablet. 100 tablets per bottle. Mild and versatile oral steroid suitable for both bulking and cutting phases.",
    inStock: true,
    rating: 4.7,
    reviews: 143,
    badge: "Best Seller",
    unitsPerPack: 100,
    dosePerUnit: "10mg",
  },
  {
    id: "29",
    name: "Anavar 50mg",
    slug: "anavar-50mg",
    category: "Bulking Steroids",
    price: 90,
    originalPrice: 115,
    image: "/images/products/anavar-50mg.webp",
    licenceUrl: "/images/products/anavar-50-2866--s256.webp",
    description: "Oxandrolone 50mg per tablet. 60 tablets per bottle. Higher-dose Anavar for significant strength and lean mass gains.",
    inStock: true,
    rating: 4.8,
    reviews: 108,
    badge: "New",
    unitsPerPack: 60,
    dosePerUnit: "50mg",
  },
  {
    id: "30",
    name: "Turinabol 10mg",
    slug: "turinabol-10mg",
    category: "Bulking Steroids",
    price: 65,
    originalPrice: 82,
    image: "/images/products/turinabol-10mg.webp",
    description: "Chlorodehydromethyltestosterone 10mg. 100 tablets. A mild oral steroid known for steady lean muscle gains without water retention.",
    inStock: true,
    rating: 4.5,
    reviews: 56,
    badge: "New",
    unitsPerPack: 100,
    dosePerUnit: "10mg",
  },
  {
    id: "40",
    name: "Winstrol 50mg",
    slug: "winstrol-50mg",
    category: "Short Cycle",
    price: 70,
    originalPrice: 88,
    image: "/images/products/winstrol-50mg.webp",
    licenceUrl: "/images/products/winstrol-50-2822--s256.webp",
    description: "Stanozolol 50mg per tablet. 100 tablets per bottle. Popular cutting and hardening steroid that promotes dry, vascular gains.",
    inStock: true,
    rating: 4.7,
    reviews: 117,
    badge: "Best Seller",
    unitsPerPack: 100,
    dosePerUnit: "50mg",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter(
    (p) => p.category.toLowerCase() === category.toLowerCase() || 
           p.category.toLowerCase().replace(/\s+/g, "-") === category.toLowerCase()
  );
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.badge === "Best Seller").slice(0, 8);
}
